amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAJLKGOJ7DXPX4PLUQ
  secretKey: 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
  bucketName: s3-bucket-test-web
  region: us-east-2
